### ISSUE TITLE
ToStorage messages should apply side affects before being emitted

### ISSUE THREAD

**Issue by LLFourn** [frostsnap/frostsnap#126]
Right now we have some logic duplication that has caused a bug and is likely to cause more. When we persist "changes" to disk the logic that applies those changes at startup after reading from disk and the logic that applies the changes in memory at the time the changes are created is different. Often developers will notice the in-memory logic being wrong but not the persisted change application logic (which requires restarting the app).

**Comment by nickfarrow** [comment]
Memory & storage persistence aligned in https://github.com/frostsnap/frostsnap/pull/138
