### ISSUE TITLE
Investigate and fix allocation failures

### ISSUE THREAD

**Issue by LLFourn** [frostsnap/frostsnap#58]
We're running out of memory frequently especially after doing multiple signings after a keygen. It always happens while decoding a new message.

This is most likely due to the way we are buffering things. We are making too many allocations to decode a single message. We should try and aim for no allocations for read buffers. There are lots of ways we are being memory inefficient all around the place but I would not fix those as yet because they will just push the problem later down the track.

I'd suggest at this stage also displaying some raw numbers on the blue boards about how much memory is being used while debugging this. I think you can do this by querying the allocator.

**Comment by nickfarrow** [comment]
After some timing practice I can get the same allocation failure (`127800`) bytes every time, just after powering on and upon the first signing attempt. You have to click OK on the downstream device ~50ms before OK on the device closer to the coordinator.

So I do think there is a read being blocked or timing issue. Signing computation on the upstream device is preventing it from reading the signature.

**Comment by LLFourn** [comment]
Ok sure. That's one way of making this happen. But you can make it happen without any timing edge cases. I've done it plenty of times. Are you saying you can't reproduce this?

**Comment by LLFourn** [comment]
Fixed by #79
