### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by orangesurf** [frostsnap/frostsnap#78]
Interested to know what hardware makes up a BlueBoard / PurpleBoard

**Comment by musdom** [comment]
"blue" or "purple" boards are what we internally call the ESP32-C3 devboards we've been using. You can get them from Aliexpress.

- [Purple board](https://www.aliexpress.com/item/1005004341489110.html) Recommended
- [Blue board](https://www.aliexpress.com/item/1005004477968500.html)

The blue board is tricky. You need to get the "NEW ESP32C3" version without USB-Serial chip. You need to get the separate Air101 display hat and solder them together. You might get a different revision of the same LCD display, which requires enabling the r2223 feature flag.

**Comment by LLFourn** [comment]
It is likely that we stop supporting these in the near future and move onto different configurations. Hopefully that is clear from the docs?
