### ISSUE TITLE
Devices should report when downstream device is disconnected to coordinator

### ISSUE THREAD

**Issue by LLFourn** [frostsnap/frostsnap#86]
- device should quickly report when downstream is disconnected on screen. It should use GPIO for this.
- should send a message to coordinator right away
- coordinator should somehow know which devices this implies are disconnected.

**Comment by nickfarrow** [comment]
> should send a message to coordinator right away

I think we currently send a debug message, but are you suggesting we send something like a `DeviceToCoordinator::DownstreamDisconnect` to the coordinator that the app can react to?

**Comment by LLFourn** [comment]
Yes :)

**Comment by LLFourn** [comment]
This was done a while ago
